version: 0.0
os: linux

# Files to deploy
files:
  - source: deploy
    destination: /home/ec2-user/adstxt-manager
    overwrite: true

# Set permissions on deployed files
permissions:
  - object: /home/ec2-user/adstxt-manager
    pattern: "**"
    owner: ec2-user
    group: ec2-user
    mode: 755

# Lifecycle hooks
hooks:
  # Stop running application before deployment
  ApplicationStop:
    - location: scripts/application_stop.sh
      timeout: 120
      runas: ec2-user
      
  # Prepare environment before installation
  BeforeInstall:
    - location: scripts/before_install.sh
      timeout: 180
      runas: ec2-user
      
  # Configure application after files are in place
  AfterInstall:
    - location: scripts/after_install.sh
      timeout: 240
      runas: ec2-user
      
  # Start the application after configuration
  ApplicationStart:
    - location: scripts/application_start.sh
      timeout: 180
      runas: ec2-user