name: Build and Deploy to S3

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'
          
      - name: Install and build backend
        run: |
          cd backend
          npm install
          npm run build
          
      - name: Install and build frontend
        run: |
          cd frontend
          npm install
          npm run build
        
      - name: Create deployment package
        run: |
          mkdir -p deploy
          cp -r backend/dist deploy/
          cp -r frontend/build deploy/public
          cp backend/package.json deploy/
          cp backend/package-lock.json deploy/
          cp Procfile deploy/
          
          # Install production dependencies without triggering scripts
          cd deploy
          npm install --omit=dev --no-scripts
          cd ..
          
          # Create zip file
          zip -r adstxt-manager.zip deploy
        
      # Upload to S3 only when running on main branch push
      - name: Upload to S3
        if: github.event_name == 'push' && github.ref == 'refs/heads/main'
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: ${{ secrets.AWS_REGION }}
        run: |
          # Check if AWS credentials are available
          if [ -z "$AWS_ACCESS_KEY_ID" ] || [ -z "$AWS_SECRET_ACCESS_KEY" ] || [ -z "$AWS_DEFAULT_REGION" ] || [ -z "${{ secrets.S3_BUCKET }}" ]; then
            echo "Error: AWS credentials or S3 bucket not configured in GitHub secrets"
            echo "Please set the following secrets in your GitHub repository:"
            echo "- AWS_ACCESS_KEY_ID"
            echo "- AWS_SECRET_ACCESS_KEY"
            echo "- AWS_REGION"
            echo "- S3_BUCKET"
            exit 1
          fi
          
          # Upload to S3
          aws s3 cp adstxt-manager.zip s3://${{ secrets.S3_BUCKET }}/adstxt-manager-${{ github.sha }}.zip
          aws s3 cp adstxt-manager.zip s3://${{ secrets.S3_BUCKET }}/adstxt-manager-latest.zip