name: Publish ads-txt-validator Package

on:
  push:
    tags:
      - 'ads-txt-validator-v*'
  workflow_dispatch:
    inputs:
      version:
        description: 'Version to publish (e.g., 1.0.1)'
        required: true
        type: string

jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          registry-url: 'https://npm.pkg.github.com'

      - name: Install dependencies
        run: |
          cd packages/ads-txt-validator
          npm install

      - name: Build package
        run: |
          cd packages/ads-txt-validator
          npm run build

      - name: Update version if workflow_dispatch
        if: github.event_name == 'workflow_dispatch'
        run: |
          cd packages/ads-txt-validator
          npm version ${{ github.event.inputs.version }} --no-git-tag-version

      - name: Publish package
        run: |
          cd packages/ads-txt-validator
          npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Create GitHub Release
        if: startsWith(github.ref, 'refs/tags/')
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: ads-txt-validator ${{ github.ref }}
          body: |
            ## ads-txt-validator Package Release
            
            This release includes the latest version of the ads-txt-validator package.
            
            ### Installation
            ```bash
            npm install @miyaichi/ads-txt-validator
            ```
            
            ### Usage
            ```typescript
            import { validateAdsTxt } from '@miyaichi/ads-txt-validator';
            
            const result = await validateAdsTxt('example.com');
            ```
          draft: false
          prerelease: false